### PR TITLE
Promise implementation

### LINKED ISSUE #24: Creation Promise class
Allow user to setup a promise, by providing it with one or multiple callback to call uppon completion of the promise.

Each callback must create a Contract object, allowing user to edit or resign the callback.
The class must throw an exception uppon edition if its already realised.

Interface proposition:

```
template<typename TType>
class Promise : public ContractProvider
{
private:

public:
    Contract subscribe(const Callback& p_callback);

    bool realised() const;

    void setValue(const TType& p_value);
    const TType& value() const;
};
```

### PR DESCRIPTION
**Pull request by NotCampeur**
Creation of a Promise class which is also a ContractProvider.
Tests can be found in the playground's main.
Accepting this PR will close #24 .

### CODE REVIEW

File: includes/threading/spk_promise.hpp [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+
+namespace spk
+{
+	template<typename TType>
+	class Promise : public ContractProvider
+	{
+	private:
+		ContractProvider::CallbackContainer _callbackContainer;
+		std::promise<TType> _promise;
+		std::optional<TType> _value;
```
Comment (EreliaCorp) [inline includes/threading/spk_promise.hpp:14]: Strangly, i thknk i wouldnt have used the std::promise at all. I would have implemented it with simply a TType value, avec an enum State, with Pending and Completed values.

Comment (EreliaCorp) [reply includes/threading/spk_promise.hpp:14]: The wait ? How do you implement it on this iteration ? You thought of a method who wait until completion ?

Comment (EreliaCorp) [reply includes/threading/spk_promise.hpp:14]: Cause if yes, i would say that there is no such need for a wait. We can send contract to the promise, who will need to call them uppon completion, so we simply need to halt the thread and provide the restart to insode the contract.

Comment (EreliaCorp) [reply includes/threading/spk_promise.hpp:14]: So, how do you wait until this spk::promise is completed ?

Comment (EreliaCorp) [reply includes/threading/spk_promise.hpp:14]: Oh, i'm stupid

**Review by EreliaCorp — APPROVED** [review]
